version: "3.7"
services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    networks:
      - envoymesh
    ports:
      - "8000:8000"

  web_service:
    build:
      context: .
      dockerfile: Dockerfile-web-service
    networks:
      - envoymesh
    ports:
      - "8080:80"

  ms_seguranca:
    build:
      context: mock-security-service
      dockerfile: Dockerfile
    networks:
      - envoymesh
    ports:
      - "9090:8000"
      
networks:
  envoymesh: {}
